name: Release

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run : docker build . -t santoshjagtap20071992/nest-app
    - run : echo  "${{secrets.DOCKER_HUB_PASSWORD}}" | docker login -u ${{secrets.DOCKER_HUB_USERNAME}} --password-stdin
    - run : docker push santoshjagtap20071992/nest-app